export const GP_RECEIPT_HEADERS = [
  "Challan No",
  "Account Receipt Note No",
  "Account Receipt Note Date",
  "SIN No",
  "Consignee Name",
  "Discom Receipt Note No",
  "Discom Receipt Note Date",
  "Rec. Challan Item No",
  "Rec. Challan Item Date",
  "TRFSI No",
  "Rating",
  "Seal No Time Of GP Received",
  "Consignee TFR Serial No",
  "Original Tfr Sr No",
  "Oil Level",
  "HV Bushing",
  "LV Bushing",
  "HT Metal Parts",
  "LT Metal Parts",
  "M and P Box",
  "M and P Box Cover",
  "MCCB",
  "ICB",
  "Copper Flexible Cable",
  "AL Wire",
  "Conservator",
  "Radiator",
  "Fuse",
  "Channel",
  "Core",
  "Poly Seal No",
  "Delivered to ACOS",
  "Remarks"
];

export const GP_RECEIPT_SAMPLE_DATA = [
  {
    "Challan No": "CH-123",
    "Account Receipt Note No": "ACC-123",
    "Account Receipt Note Date": "2024-01-01",
    "SIN No": "SIN-123",
    "Consignee Name": "Consignee Name",
    "Discom Receipt Note No": "DIS-123",
    "Discom Receipt Note Date": "2024-01-01",
    "Rec. Challan Item No": "REC-001",
    "Rec. Challan Item Date": "2024-01-05",
    "TRFSI No": "TRFSI-123",
    "Rating": "100",
    "Seal No Time Of GP Received": "SEAL-123",
    "Consignee TFR Serial No": "TFR-123",
    "Original Tfr Sr No": "SR-123",
    "Oil Level": "OK",
    "HV Bushing": "OK",
    "LV Bushing": "OK",
    "HT Metal Parts": "OK",
    "LT Metal Parts": "OK",
    "M and P Box": "OK",
    "M and P Box Cover": "OK",
    "MCCB": "OK",
    "ICB": "OK",
    "Copper Flexible Cable": "OK",
    "AL Wire": "OK",
    "Conservator": "OK",
    "Radiator": "OK",
    "Fuse": "OK",
    "Channel": "OK",
    "Core": "OK",
    "Poly Seal No": "POLY-123",
    "Delivered to ACOS": "Yes",
    "Remarks": "Some remarks"
  }
];
